-- NMSPL Employees Table Setup for Supabase
-- Generated: 2026-03-26
-- Total employees: 320

-- Create table
CREATE TABLE IF NOT EXISTS nmspl_employees (
    emp_id      TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    role        TEXT,
    designation TEXT,
    location    TEXT
);

-- Enable Row Level Security
ALTER TABLE nmspl_employees ENABLE ROW LEVEL SECURITY;

-- Policy: allow public (anon) read access
CREATE POLICY "Allow public read access"
    ON nmspl_employees
    FOR SELECT
    TO anon
    USING (true);

-- Insert all employees
INSERT INTO nmspl_employees (emp_id, name, role, designation, location) VALUES
    ('NM1001', 'Nagendra Mali', 'MD', 'Chairman And Managing Director', 'Head Office'),
    ('NM1004', 'Ganesh Khajurkar', 'Leader', 'Chief Accounts Officer', 'Head Office'),
    ('NM1014', 'Subhas Nagappa Nagannanavar', 'AM_MBL', 'Senior Area Manager', 'Haveri'),
    ('NM1030', 'Krishnappa K', 'FO', 'Field Officer', 'Shikaripura'),
    ('NM1091', 'Fakkiresh Basavantappa Parvatiyavar', 'BM', 'Branch Manager', 'Shiggaon'),
    ('NM1679', 'Chanabasappa Shekappa Mattur', 'BM', 'Branch Manager', 'Haveri'),
    ('NM1819', 'Altaf Basur', 'BM', 'Branch Manager', 'Byadagi'),
    ('NM1831', 'Vinayak M Manegar', 'Manager', 'Deputy Manager - MIS', 'Head Office'),
    ('NM2018', 'Santhosh H Harijan', 'BM', 'Branch Manager', 'Anavatti'),
    ('NM2083', 'Malkeshwar Kamble', 'DM', 'Divisional Manager', 'Kagal'),
    ('NM2131', 'Malleshappa Shivamurteppa Kariyannanavar', 'FO', 'Branch In-Charge', 'Ranebennur'),
    ('NM2318', 'Shashidhara Puttappa Tavari', 'Executive', 'Senior Execuitve - MIS', 'Head Office'),
    ('NM2382', 'Pandurangappa Katenahalli', 'BM', 'Branch Manager', 'Hirekerur'),
    ('NM2439', 'Murthy Ujjer', 'AM', 'Area Manager', 'Shimoga'),
    ('NM2482', 'C Kotragouda', 'CH', 'Collection Head', 'Head Office'),
    ('NM2651', 'Nagaraj Walmiki', 'FO', 'Field Officer', 'Shiggaon'),
    ('NM2674', 'Kumar Mallammanavar', 'RM_MBL', 'Relationship Manager', 'Haveri'),
    ('NM2705', 'Gurupadappa Yaligar', 'Assistant', 'Office Boy', 'Head Office'),
    ('NM2742', 'Shridhar Vijay Powar', 'FO', 'Field Officer', 'Tasgaon'),
    ('NM2778', 'Lingraj F. Parvatiyavar', 'BM', 'Branch Manager', 'Guttal'),
    ('NM2882', 'Sunil Uppar', 'FO', 'Field Officer', 'Shiggaon'),
    ('NM2916', 'Shivappa Lakshmana Hosamani', 'FO', 'Field Officer', 'Byadagi'),
    ('NM2944', 'Gajendragouda Patil', 'FO', 'Field Officer', 'Byadagi'),
    ('NM2954', 'Shivu N', 'BM', 'Branch In-Charge', 'Shimoga'),
    ('NM3030', 'Naginabhanu M Makandar', 'Executive', 'Senior Executive - Operations', 'Head Office'),
    ('NM3036', 'Puttayya Shankrayya Kanti', 'BM', 'Branch Manager', 'Akkialur'),
    ('NM3175', 'Siddaraju H K', 'IA', 'Executive-Audit', 'Ramanagara'),
    ('NM3249', 'Sachin N R', 'AM', 'Area Manager', 'Belur'),
    ('NM3342', 'M R Kumar', 'FO', 'Senior Field Officer', 'Ramanagara'),
    ('NM3418', 'Roopesha M  M', 'BM', 'Branch Manager', 'Mandya'),
    ('NM3453', 'Pavitra Angadi', 'Executive', 'Executive - MIS', 'Head Office'),
    ('NM3462', 'Shivakumar M', 'BM', 'Branch Manager', 'Kanakapura'),
    ('NM3654', 'Prasanna Kumara A', 'BM', 'Branch Manager', 'Piriyapattana'),
    ('NM3666', 'Bhuvaneshwari R', 'BOE', 'Branch Operation Executive', 'Ramanagara'),
    ('NM3676', 'Prakash Gudagur', 'Manager', 'Manager - Accounts', 'Head Office'),
    ('NM3680', 'Vikas H R', 'FO', 'Field Officer', 'Bellur Cross'),
    ('NM3785', 'Santhosha Naik T', 'FO', 'Field Officer', 'Shikaripura'),
    ('NM3841', 'Parashivamurthy T D', 'FO', 'Branch In-Charge', 'H D Kote'),
    ('NM3856', 'Jayesh Vinayak Chavan', 'FO', 'Branch In-Charge', 'Kolhapur'),
    ('NM3867', 'Amol Madhukar Salokhe', 'Executive', 'Executive-Legal', 'Sangli'),
    ('NM3871', 'Siddaraju S', 'BM', 'Branch Manager', 'Kollegal'),
    ('NM3925', 'Basavaraj Negalur', 'BM_MBL', 'Branch Manager', 'Haveri'),
    ('NM3926', 'Sarjerao Dattatray Yamagar', 'FO', 'Field Officer', 'Tasgaon'),
    ('NM3949', 'Chandrashekhar', 'FO', 'Field Officer', 'Kollegal'),
    ('NM3980', 'M Ragul', 'BM', 'Branch In-Charge', 'Gudiyatham'),
    ('NM3990', 'Prasanth Vengatesan', 'BM', 'Branch Manager', 'Alagayam'),
    ('NM4013', 'Vinoth Kumar Annamalai', 'FO', 'Field Officer', 'Alagayam'),
    ('NM4044', 'Madhu M B', 'BM', 'Branch Manager', 'KR Pete'),
    ('NM4080', 'Ravichandra G', 'BM', 'Branch In-Charge', 'Magadi'),
    ('NM4113', 'B S Rajesha', 'FO', 'Branch In-Charge', 'Piriyapattana'),
    ('NM4133', 'Ravi Harijan', 'FO', 'Field Officer', 'Guttal'),
    ('NM4142', 'Darshan B J', 'FO', 'Field Officer', 'KR Pete'),
    ('NM4144', 'Chethan Kumar C', 'BM', 'Branch In-Charge', 'Santhemarhalli'),
    ('NM4152', 'Thangaraj Muniyappan', 'FO', 'Branch In-Charge', 'Krishnagiri'),
    ('NM4227', 'Keerthikumar', 'FO', 'Field Officer', 'KR Pete'),
    ('NM4274', 'Rachappaji C', 'BM', 'Branch In-Charge', 'Malavalli'),
    ('NM4298', 'Mahendren Arvindhan', 'FO', 'Branch In-Charge', 'Palacode'),
    ('NM4313', 'Sarathkumar A', 'FO', 'Field Officer', 'Arani'),
    ('NM4337', 'Manjunatha  H U', 'IA', 'Executive-Audit', 'Gundlapete'),
    ('NM4427', 'Janardhana V', 'ABM', 'Branch In-Charge', 'Kanakapura'),
    ('NM4547', 'Surendra H.P', 'AM', 'Area Manager', 'Mandya'),
    ('NM4607', 'Santhosha M C', 'AM', 'Area Manager', 'K R Nagara'),
    ('NM4615', 'Althaf M Horakeri', 'BM', 'Branch Manager', 'Mundgod'),
    ('NM4645', 'Chinnasamy Vajjiravel', 'FO', 'Field Officer', 'Palacode'),
    ('NM4662', 'Jennifer', 'Executive', 'Senior Executive - Finance', 'Corporate Office'),
    ('NM4757', 'Arun T J', 'RO_ MBL', 'Relationship officer', 'Shikaripura'),
    ('NM4794', 'Vinod Raj', 'FO', 'Field Officer', 'Hunsur'),
    ('NM4853', 'Vijay Thiyagaraj', 'FO', 'Field Officer', 'Denkanikottai'),
    ('NM4855', 'Jegatheesh', 'FO', 'Field Officer', 'Alagayam'),
    ('NM4878', 'Kariyappa Dyamannanavar', 'FO', 'Field Officer', 'Byadagi'),
    ('NM4989', 'Ravi Parasappa Padeppanavar', 'ACM_ MBL', 'Area Credit Manager', 'Haveri'),
    ('NM5106', 'Jayashree Pasupathy', 'DOX', 'Divisional Executive - Operation', 'Krishnagiri'),
    ('NM5116', 'Fakrusab Shareefsab Hanchinal', 'FO', 'Field Officer', 'Mundgod'),
    ('NM5132', 'Varun V R', 'FO', 'Field Officer', 'Ramanagara'),
    ('NM5213', 'Anilkumar Chikkappa Sangannanavar', 'FO', 'Field Officer', 'Ranebennur'),
    ('NM5217', 'S Sivaprakasam', 'IA', 'Executive - Internal Audit', 'Krishnagiri'),
    ('NM5265', 'Manjunatha Nayaka R', 'IA', 'Executive-Audit', 'Mysore'),
    ('NM5267', 'Shivaraj Basavaraj Harijan', 'FO', 'Field Officer', 'Anavatti'),
    ('NM5300', 'Ajit Subhash Gaikwad', 'FO', 'Field Officer', 'Mangalwad'),
    ('NM5316', 'Hamsha H K', 'DOX', 'Divisional Executive - Operation', 'Mysore'),
    ('NM5360', 'Nandan Bhajantri', 'FO', 'Field Officer', 'Haveri'),
    ('NM5489', 'Chandan H R', 'FO', 'Field Officer', 'Mandya'),
    ('NM5540', 'Manikandan Vadivel', 'FO', 'Field Officer', 'Mettur'),
    ('NM5590', 'Karthik Boobathi', 'FO', 'Senior Field Officer', 'Nataramballi'),
    ('NM5638', 'Santhosh Kumar', 'FO', 'Field Officer', 'Arani'),
    ('NM5662', 'B C Singappa', 'FO', 'Field Officer', 'Nyamati'),
    ('NM5667', 'Eregowda K J', 'FO', 'Field Officer', 'Mysore'),
    ('NM5695', 'Sandeep K J', 'IA', 'Executive-Audit', 'Hassan'),
    ('NM5711', 'Sudhakara H S', 'FO', 'Field Officer', 'KR Pete'),
    ('NM5713', 'Premkumar H Harijana', 'BM', 'Branch Manager', 'Shikaripura'),
    ('NM5719', 'Dhandapani P', 'FO', 'Senior Field Officer', 'Gudiyatham'),
    ('NM5724', 'Sandip Pandurang Korane', 'BM', 'Branch Manager', 'Kolhapur'),
    ('NM5729', 'Beerendramurthy C R', 'FO', 'Field Officer', 'Gundlapete'),
    ('NM5732', 'Chethan', 'AM', 'Area Manager', 'Gundlapete'),
    ('NM5746', 'Balaganesh K R', 'FO', 'Field Officer', 'Krishnagiri'),
    ('NM5758', 'Mallikarjuna', 'FO', 'Field Officer', 'Nyamati'),
    ('NM5788', 'Ajay S', 'FO', 'Field Officer', 'Malavalli'),
    ('NM5800', 'Manigandan B', 'FO', 'Senior Field Officer', 'Arani'),
    ('NM5818', 'Manikanta M', 'FO', 'Field Officer', 'Shimoga'),
    ('NM5829', 'Marappan Chinnasamy', 'BM', 'Branch Manager', 'Anthiyur'),
    ('NM5834', 'Sathisha P', 'BM', 'Branch In-Charge', 'Hassan'),
    ('NM5850', 'Shankara C', 'DM', 'Divisional Manager', 'Mysore'),
    ('NM5866', 'N D Santhosh', 'FO', 'Field Officer', 'Holenarasipura'),
    ('NM5870', 'Raju N', 'FO', 'Field Officer', 'Santhemarhalli'),
    ('NM5877', 'Raman A', 'BM', 'Branch In-Charge', 'Arani'),
    ('NM5890', 'Sharmila Palanisamy', 'BOE', 'Branch Operation-Executive', 'Annur'),
    ('NM5948', 'Shivaprasad C M', 'FO', 'Field Officer', 'Malavalli'),
    ('NM5950', 'SANTOSH S MATTIHALLI', 'BM', 'Branch Manager', 'Hirekerur'),
    ('NM5978', 'Delhiganesh Loganathan', 'FO', 'Field Officer', 'Nataramballi'),
    ('NM6012', 'Dinesh Shashikant Kale', 'FO', 'Field Officer', 'Solapur'),
    ('NM6043', 'Arunkumar H R', 'FO', 'Field Officer', 'Piriyapattana'),
    ('NM6051', 'Murulidhara', 'FO', 'Field Officer', 'Anavatti'),
    ('NM6053', 'Venkatesha', 'FO', 'Field Officer', 'Gundlapete'),
    ('NM6077', 'Nayana', 'BOE', 'Branch Operation-Executive', 'Bellur Cross'),
    ('NM6078', 'Devaraju T', 'BM', 'Branch Manager', 'Hunsur'),
    ('NM6086', 'KUMARA  M', 'IA', 'Divsional Manager-Audit', 'Mysore'),
    ('NM6097', 'Prajwal Mulagund', 'Manager', 'Assistant Manager - Operations', 'Head Office'),
    ('NM6101', 'Akhilesh Kumar Patel', 'DHR', 'Divisional Executive - HR', 'Chhindwara'),
    ('NM6113', 'ANIL KUMAR S  S', 'FO', 'Field Officer', 'Holenarasipura'),
    ('NM6116', 'Swamy B', 'FO', 'Field Officer', 'Mysore'),
    ('NM6136', 'Pavithra M', 'BM', 'Branch In-Charge', 'Bellur Cross'),
    ('NM6139', 'Anju', 'FO', 'Field Officer', 'Piriyapattana'),
    ('NM6143', 'Harisha S', 'FO', 'Field Officer', 'Hunsur'),
    ('NM6152', 'Praveenakayakada', 'FO', 'Field Officer', 'Guttal'),
    ('NM6153', 'Chandrappa S', 'BM', 'Branch Manager', 'Nyamati'),
    ('NM6170', 'Girish', 'AM', 'Area Manager', 'Akkialur'),
    ('NM6173', 'Gaurav Vishwkarma', 'FO', 'Field Officer', 'Junnardeo'),
    ('NM6176', 'Durgesh', 'BM', 'Branch Manager', 'Chhapara'),
    ('NM6178', 'Vijaykumar S Kattimani', 'FO', 'Field Officer', 'Hirekerur'),
    ('NM6184', 'Chandra', 'FO', 'Field Officer', 'Hunsur'),
    ('NM6192', 'CHOUGULE ANIL MALLANNA', 'BM', 'Branch Manager', 'Solapur'),
    ('NM6196', 'Anjali', 'FO', 'Field Officer', 'Srirangapatna'),
    ('NM6207', 'Firdosh khan', 'AM', 'Area Manager', 'Khategaon'),
    ('NM6214', 'DHIRAJ DAYANAND ZENDE', 'BM', 'Branch Manager', 'Tasgaon'),
    ('NM6233', 'Sowndhar Pachamuthu', 'AM', 'Area Manager', 'Mettur'),
    ('NM6237', 'S Vishnu', 'FO', 'Field Officer', 'Solingar'),
    ('NM6238', 'Mamtha M', 'BOE', 'Branch Operation-Executive', 'Denkanikottai'),
    ('NM6240', 'GIRISHA NAYAKA K R', 'FO', 'Field Officer', 'Hassan'),
    ('NM6244', 'Altaf Doddamani', 'RM_MBL', 'Relationship Manager', 'Ranebennur'),
    ('NM6252', 'Anand kumar yadav', 'BM', 'Branch Manager', 'Junnardeo'),
    ('NM6265', 'Praveen Bharti', 'FO', 'Field Officer', 'Narmadapuram'),
    ('NM6269', 'CHAITHRA H K', 'DOX', 'Divisional Executive - Operation', 'Channarayapattana'),
    ('NM6299', 'Lokesh S', 'FO', 'Field Officer', 'Alagayam'),
    ('NM6300', 'seenivasan B', 'FO', 'Field Officer', 'Alagayam'),
    ('NM6302', 'Venkatachalam G', 'BM', 'Branch Manager', 'Palacode'),
    ('NM6303', 'Jayavel D R', 'BM', 'Branch Manager', 'Solingar'),
    ('NM6306', 'Krishna Kumar Dehariya', 'FO', 'Field Officer', 'Bicchua'),
    ('NM6317', 'Avula Jayasri', 'BOE', 'Branch Operation-Executive', 'Rajampet'),
    ('NM6325', 'Sachin H', 'FO', 'Field Officer', 'Shikaripura'),
    ('NM6332', 'Maheshwar Singh kushwah', 'IA', 'Executive-Audit', 'Junnardeo'),
    ('NM6340', 'RAJNI', 'FO', 'Field Officer', 'Chhapara'),
    ('NM6342', 'Adarsh Soni', 'FO', 'Field Officer', 'Chhindwara'),
    ('NM6344', 'Manish Sahu', 'FO', 'Field Officer', 'Junnardeo'),
    ('NM6346', 'Shridhar Ravindra Jadhav', 'FO', 'Field Officer', 'Tasgaon'),
    ('NM6349', 'Shital Dipak Patil', 'BM', 'Branch Manager', 'Sangli'),
    ('NM6378', 'KRISHNA MURTHY', 'FO', 'Field Officer', 'Shimoga'),
    ('NM6384', 'Surendra Yadav', 'FO', 'Field Officer', 'Chhindwara'),
    ('NM6385', 'Anil Kushwah', 'BM', 'Branch In-Charge', 'Junnardeo'),
    ('NM6388', 'ANIL N JAMADAR', 'Manager', 'Assistant Manager-HR', 'Head Office'),
    ('NM6403', 'Maruthi K H', 'BM', 'Branch Manager', 'Ranebennur'),
    ('NM6405', 'Kunal Yadav', 'FO', 'Field Officer', 'Junnardeo'),
    ('NM6412', 'M Manoj', 'FO', 'Field Officer', 'K R Nagara'),
    ('NM6420', 'DEEKSHITH G J', 'BM', 'Branch In-Charge', 'Arakalagud'),
    ('NM6427', 'Prajapati Pandurang Kamble', 'FO', 'Field Officer', 'Kolhapur'),
    ('NM6439', 'Basavaraddi Kotaraddi Maidur', 'FO', 'Field Officer', 'Guttal'),
    ('NM6440', 'Shantappa Ningappa Hadimani', 'FO', 'Branch In-Charge', 'Guttal'),
    ('NM6452', 'Pavan S', 'FO', 'Field Officer', 'Malavalli'),
    ('NM6460', 'Harish Prasath T', 'FO', 'Field Officer', 'Alagayam'),
    ('NM6469', 'Anbeeswaran Krishnan', 'BM', 'Branch Manager', 'Anthiyur'),
    ('NM6471', 'VIJAYAKUMAR ANNAMALAI', 'FO', 'Senior Field Officer', 'Krishnagiri'),
    ('NM6495', 'Abinayabharathi Annadhurai', 'FO', 'Field Officer', 'Anthiyur'),
    ('NM6508', 'Umesh Dattatray Jangam', 'FO', 'Field Officer', 'Kagal'),
    ('NM6512', 'Mukesh Yadav', 'FO', 'Field Officer', 'Chhapara'),
    ('NM6521', 'Raja Kailasam', 'FO', 'Field Officer', 'Krishnagiri'),
    ('NM6533', 'ASHWINI DEEPAK PATIL', 'FO', 'Field Officer', 'Sangli'),
    ('NM6546', 'Madesh', 'FO', 'Field Officer', 'Palacode'),
    ('NM6573', 'A Shebiya', 'FO', 'Field Officer', 'Annur'),
    ('NM6578', 'SIVASANKAR K', 'FO', 'Field Officer', 'Arani'),
    ('NM6585', 'Harshavardhan K N', 'FO', 'Field Officer', 'Mandya'),
    ('NM6592', 'Gobindi', 'FO', 'Field Officer', 'Junnardeo'),
    ('NM6594', 'Vinoth Kumaran', 'FO', 'Field Officer', 'Alagayam'),
    ('NM6595', 'Pooja Manikkam', 'BOE', 'Branch Operation-Executive', 'Krishnagiri'),
    ('NM6605', 'Sachin', 'BM', 'Branch Manager', 'Mysore'),
    ('NM6621', 'Chethan B D', 'BM', 'Branch In-Charge', 'K R Nagara'),
    ('NM6629', 'Rahul Annasaheb Baravkar', 'FO', 'Field Officer', 'Solapur'),
    ('NM6634', 'Gundugallu Harish', 'FO', 'Field Officer', 'Rajampet'),
    ('NM6639', 'Akash Barkhane', 'FO', 'Field Officer', 'Chhindwara'),
    ('NM6651', 'Parameshwari S', 'BOE', 'Branch Operation-Executive', 'Chengam'),
    ('NM6652', 'Prathap R', 'FO', 'Branch In-Charge', 'Solingar'),
    ('NM6653', 'Irfan Mansuri', 'FO', 'Field Officer', 'Chhindwara'),
    ('NM6656', 'Govind Prasad Chaudhary', 'DM', 'Divisional Manager', 'Chhapara'),
    ('NM6657', 'Mohanraj Thimmarayan', 'AM', 'Area Manager', 'Krishnagiri'),
    ('NM6667', 'Nitesh', 'FO', 'Field Officer', 'Bicchua'),
    ('NM6692', 'SIVASANGAVAI', 'FO', 'Senior Field Officer', 'Udamalpet'),
    ('NM6710', 'Manoj Jat', 'FO', 'Field Officer', 'Khategaon'),
    ('NM6723', 'Sathiya kumar R', 'ABM', 'Branch In-Charge', 'Illupur'),
    ('NM6724', 'C Karthi', 'FO', 'Field Officer', 'Anthiyur'),
    ('NM6743', 'Jeevan R', 'FO', 'Field Officer', 'Holenarasipura'),
    ('NM6747', 'Maruti Kodad', 'FO', 'Field Officer', 'Byadagi'),
    ('NM6751', 'Lokesh M N', 'FO', 'Field Officer', 'K R Nagara'),
    ('NM6752', 'RAKESH HR', 'FO', 'Field Officer', 'Holenarasipura'),
    ('NM6755', 'CHAITHANYA', 'FO', 'Field Officer', 'Belur'),
    ('NM6768', 'Madhu Kaginelli', 'BOE', 'Branch Operation-Executive', 'Akkialur'),
    ('NM6788', 'Jakkula Venkatesh', 'FO', 'Field Officer', 'Nirmal'),
    ('NM6802', 'Honnagouda Chanabasanagouda Marigoudra', 'FO', 'Field Officer', 'Akkialur'),
    ('NM6804', 'Ravi Sadanand Naik', 'BM', 'Branch Manager', 'Honnavar'),
    ('NM6822', 'Muthukumar Ayyanar', 'AM', 'Area Manager', 'Annur'),
    ('NM6823', 'Aris Rayappan', 'BM', 'Branch Manager', 'Palacode'),
    ('NM6825', 'Santhiya Narayanasamy', 'BOE', 'Branch Operation-Executive', 'Mettur'),
    ('NM6834', 'Rajashekar  H S', 'FO', 'Field Officer', 'Piriyapattana'),
    ('NM6842', 'Murali S', 'AM', 'Area Manager', 'Chengam'),
    ('NM6849', 'Srinivasa B G', 'FO', 'Field Officer', 'Magadi'),
    ('NM6858', 'Vidhyashree J', 'FO', 'Senior Field Officer', 'Srirangapatna'),
    ('NM6881', 'Parashurama Malad Kar', 'FO', 'Field Officer', 'Anavatti'),
    ('NM6882', 'Rajalakshmi A R', 'BM', 'Branch In-Charge', 'Channarayapattana'),
    ('NM6885', 'Nitin kumar K E', 'FO', 'Senior Field Officer', 'KR Pete'),
    ('NM6790', 'BITLA VANITHA', 'ABM', 'Branch In-Charge', 'Nirmal'),
    ('NM6912', 'Mohsin Khan', 'DOX', 'Divisional Executive - Operation', 'Khategaon'),
    ('NM6913', 'Ghanshyam Mishra', 'BM', 'Branch In-Charge', 'Narmadapuram'),
    ('NM6918', 'Mosin Khan', 'FO', 'Field Officer', 'Mysore'),
    ('NM6931', 'Vijayakumar Mani', 'IA', 'Executive - Internal Audit', 'Mettur'),
    ('NM6935', 'Vinutha J S', 'BM', 'Branch Manager', 'Srirangapatna'),
    ('NM6939', 'Dinesh', 'FO', 'Field Officer', 'Gudiyatham'),
    ('NM6941', 'Gokulraj  G', 'IA', 'Divisional Manager - Internal Audit', 'Krishnagiri'),
    ('NM6960', 'Varalakshmi D', 'FO', 'Field Officer', 'Kanakapura'),
    ('NM6961', 'Pooja T', 'FO', 'Field Officer', 'Kanakapura'),
    ('NM6963', 'Arjuna', 'FO', 'Field Officer', 'Mysore'),
    ('NM6973', 'Umesha N', 'FO', 'Field Officer', 'Anavatti'),
    ('NM6975', 'S dhivya', 'BM', 'Branch Manager', 'Illupur'),
    ('NM6980', 'Akkidasari Yebbej', 'FO', 'Field Officer', 'Rajampet'),
    ('NM6987', 'Rakesh Rodekar', 'FO', 'Senior Field Officer', 'Katangi'),
    ('NM7018', 'Vijai Krishnamurthi', 'FO', 'Field Officer', 'Anthiyur'),
    ('NM7019', 'Sridevi Chelladurai', 'FO', 'Field Officer', 'Anthiyur'),
    ('NM7034', 'Sachin Mahadeorao Tayde', 'AM', 'Area Manager', 'Kolhapur'),
    ('NM7038', 'Gaikwad Punnam Kumar', 'BM', 'Branch Manager', 'Nirmal'),
    ('NM7049', 'Karthikeyan Jaganathan', 'FO', 'Field Officer', 'Nataramballi'),
    ('NM7069', 'Sanjai Anbazhagan', 'FO', 'Field Officer', 'Solingar'),
    ('NM7078', 'Dileep D M', 'FO', 'Field Officer', 'K R Nagara'),
    ('NM7118', 'Karthik M k', 'FO', 'Field Officer', 'Arakalagud'),
    ('NM7133', 'Basavaraju', 'FO', 'Field Officer', 'H D Kote'),
    ('NM7150', 'Subashchandrabose M', 'BM', 'Branch Manager', 'Nataramballi'),
    ('NM7217', 'Viji R', 'BM', 'Branch Manager', 'Thiruchangode'),
    ('NM7218', 'Manivannan M', 'FO', 'Field Officer', 'Anthiyur'),
    ('NM7234', 'Omsakthi Thimman', 'BM', 'Branch Manager', 'Krishnagiri'),
    ('NM7240', 'Puneethkumar Badakariyappanavar', 'FO', 'Field Officer', 'Haveri'),
    ('NM7241', 'Jagadeesha Timmappa Naik', 'FO', 'Field Officer', 'Honnavar'),
    ('NM7242', 'Gowtham  R D', 'BM', 'Branch In-Charge', 'Belur'),
    ('NM7251', 'Vishava S', 'FO', 'Field Officer', 'Chengam'),
    ('NM7262', 'Pooja Sanodiya', 'FO', 'Field Officer', 'Chhapara'),
    ('NM7265', 'RANJAN S', 'BM', 'Branch Manager', 'Holenarasipura'),
    ('NM7279', 'Soundarrajan Shanmugam', 'FO', 'Field Officer', 'Mettur'),
    ('NM7284', 'Rajini A K', 'BOE', 'Branch Operation-Executive', 'Hassan'),
    ('NM7287', 'Vediyappan', 'BM', 'Branch In-Charge', 'Chengam'),
    ('NM7291', 'Kumar C', 'FO', 'Field Officer', 'H D Kote'),
    ('NM7294', 'Siddaramayya Hiremath', 'FO', 'Field Officer', 'Mundgod'),
    ('NM7297', 'Vinay  Kanthi', 'FO', 'Field Officer', 'Mundgod'),
    ('NM7298', 'Ashwini Nagappa Hosamani', 'Executive', 'Executive - Admin', 'Haveri'),
    ('NM7299', 'Bharath B', 'FO', 'Field Officer', 'Kollegal'),
    ('NM7303', 'Kaviya G', 'BOE', 'Branch Operation-Executive', 'Gudiyatham'),
    ('NM7306', 'Bhyranayaka S', 'FO', 'Field Officer', 'Kollegal'),
    ('NM7307', 'Shreenivasa  T V', 'IA', 'Divsional Manager-Audit', 'Head Office'),
    ('NM7309', 'Gowramma', 'FO', 'Field Officer', 'H D Kote'),
    ('NM7310', 'Shivanna K M', 'FO', 'Field Officer', 'Hunsur'),
    ('NM7311', 'Basavaraj Hombaradi', 'IA', 'Executive-Audit', 'Haveri'),
    ('NM7312', 'A Saranya', 'FO', 'Field Officer', 'Gudiyatham'),
    ('NM7316', 'Arjun', 'FO', 'Field Officer', 'Khategaon'),
    ('NM7317', 'Rangaswamy', 'FO', 'Field Officer', 'T Narasipura'),
    ('NM7319', 'Sagar Gunavant Singe', 'BM', 'Branch Manager', 'Kagal'),
    ('NM7320', 'Karthik E', 'BM', 'Branch Manager', 'Mettur'),
    ('NM7321', 'Sandhiya M', 'FO', 'Field Officer', 'Mettur'),
    ('NM7325', 'Rakshith', 'FO', 'Field Officer', 'Gundlapete'),
    ('NM7326', 'Hema', 'FO', 'Field Officer', 'Channarayapattana'),
    ('NM7327', 'Kathirvalavan M', 'FO', 'Field Officer', 'Chengam'),
    ('NM7329', 'Mohan Chandrakant Naik', 'BM', 'Branch Manager', 'Gadhinglaj'),
    ('NM7330', 'Amol Pradip Vise', 'FO', 'Field Officer', 'Sangli'),
    ('NM7331', 'Pradnyavant balasaheb varale', 'FO', 'Field officer', 'Gadhinglaj'),
    ('NM7332', 'Mannuru hari', 'FO', 'Field Officer', 'Rajampet'),
    ('NM7333', 'Madhu Kumar', 'FO', 'Field Officer', 'Mysore'),
    ('NM7334', 'Adithya S N', 'FO', 'Field Officer', 'K R Nagara'),
    ('NM7340', 'Ragul K Kaliyaperumal', 'FO', 'Field Officer', 'Palacode'),
    ('NM7341', 'Prasanthkumar S', 'FO', 'Field Officer', 'Denkanikottai'),
    ('NM7342', 'Patiram Mordhare', 'FO', 'Field Officer', 'Bicchua'),
    ('NM7343', 'Huchhappa M', 'FO', 'Senior Field officer', 'Mysore'),
    ('NM7346', 'Madhukumar D Annigeri', 'Assistant', 'Assistant-Admin', 'Head Office'),
    ('NM7347', 'Muskan Sarathe', 'ABM', 'Branch In-Charge', 'Chhindwara'),
    ('NM7348', 'Prasanna H M', 'FO', 'Field Officer', 'Hassan'),
    ('NM7349', 'Ramkumar Mehra', 'FO', 'Field Officer', 'Narmadapuram'),
    ('NM7350', 'Abhinav Singh', 'ABM', 'Branch In-Charge', 'Katangi'),
    ('NM7352', 'Balasaheb Vishnu Kamble', 'FO', 'Field Officer', 'Gadhinglaj'),
    ('NM7353', 'Laxmi Narre', 'BM', 'Branch Manager', 'Bicchua'),
    ('NM7354', 'Venugopala', 'BM', 'Branch Manager', 'H D Kote'),
    ('NM7355', 'Prabhakar Mohan Sunchu', 'IA', 'Executive - Internal Audit', 'Solapur'),
    ('NM7357', 'Likhitha HS', 'FO', 'Field Officer', 'Arakalagud'),
    ('NM7358', 'Nanjundaswamy B', 'FO', 'Field Officer', 'T Narasipura'),
    ('NM7359', 'Abhilash S', 'FO', 'Field Officer', 'T Narasipura'),
    ('NM7361', 'Monika S', 'BOE', 'Branch Operation Executive', 'Arani'),
    ('NM7363', 'Boga Krishna Mohan', 'BM', 'Branch Manager', 'Rajampet'),
    ('NM7364', 'Chandrakala U N', 'FO', 'Field Officer', 'Channarayapattana'),
    ('NM7366', 'Channabasappa Keri', 'FO', 'Field officer', 'Shiggaon'),
    ('NM7368', 'Dadafeer Kabbar', 'IA', 'Executive - Internal Audit', 'Hirekerur'),
    ('NM7370', 'Kanchana', 'FO', 'Field Officer', 'Channarayapattana'),
    ('NM7371', 'Nandhakumar G', 'BM', 'Branch Manager', 'Udamalpet'),
    ('NM7372', 'Mahendra Manik', 'FO', 'Senior Field Officer', 'Khategaon'),
    ('NM7374', 'Karthik  K S', 'FO', 'Field Officer', 'Mandya'),
    ('NM7377', 'Beerappa Karoor', 'FO', 'Senior Field Officer', 'Ranebennur'),
    ('NM7378', 'Chandra R', 'FO', 'Field Officer', 'Srirangapatna'),
    ('NM7379', 'Rahul Kumar', 'CS', 'Company Secretory', 'Corporate Office'),
    ('NM7381', 'Chaithra H M', 'FO', 'Field Officer', 'Channarayapattana'),
    ('NM7382', 'Ranjit Ramchandra Patil', 'FO', 'Senior Field Officer', 'Kolhapur'),
    ('NM7383', 'M Raju', 'BM', 'Branch Manager', 'T Narasipura'),
    ('NM7384', 'Kowsika R', 'BOE', 'Branch Operation Executive', 'Anthiyur'),
    ('NM7385', 'Nitin Shrimant Mane', 'FO', 'Field Officer', 'Mangalwad'),
    ('NM7386', 'Nikhil K M', 'ABM', 'Branch In-Charge', 'Gundlapete'),
    ('NM7387', 'R Harinath', 'FO', 'Field Officer', 'Gudiyatham'),
    ('NM7388', 'Lokesh', 'FO', 'Field Officer', 'Magadi'),
    ('NM7389', 'Shalini H B', 'FO', 'Senior Field Officer', 'Arakalagud'),
    ('NM7391', 'Akash Sanjay Sonule', 'FO', 'Field Officer', 'Kagal'),
    ('NM7392', 'Laxman', 'FO', 'Senior Field Officer', 'Khategaon'),
    ('NM7393', 'Ananya AC', 'BOE', 'Branch Operation-Executive', 'Bellur Cross'),
    ('NM7394', 'Omkar H R', 'FO', 'Field Officer', 'T Narasipura')
ON CONFLICT (emp_id) DO NOTHING;
